### ISSUE TITLE
As an admin, i want to search and sort users in users page

### ISSUE THREAD

**Issue by eloravpn** [eloravpn/EloraVPNManager#2]
### Search by:

- Name and Last name
- Telegram username and chat-id

### Sort by:
- Created
- Modified
- Number of accounts

**Comment by abhinaisai2002** [comment]
Hey, can i work on this feature?

**Comment by eloravpn** [comment]
Hi Abhinai 
Yeah 💯 Welcome!

**Comment by abhinaisai2002** [comment]
Can you help me set up the project locally, i am facing some issues

**Comment by abhinaisai2002** [comment]
raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SUBSCRIPTION_BASE_URL not found. Declare it as envvar or define a default value.

I am getting this when running the python script
Can you help me resolving this

**Comment by eloravpn** [comment]
Do yout read the help?
https://github.com/eloravpn/EloraVPNManager#how-to-install

Also i fixed this issue yesterday

**Comment by eloravpn** [comment]
> raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option)) decouple.UndefinedValueError: SUBSCRIPTION_BASE_URL not found. Declare it as envvar or define a default value.
> 
> I am getting this when running the python script Can you help me resolving this

Pleas update your fork to latest version

**Comment by abhinaisai2002** [comment]
it is redirecting me to login page, how to create a account in this?

**Comment by eloravpn** [comment]
default sudoer username and password is admin.

also you can change it in `.env` file based on `src/config.py`,
the environment varaibles is `SUDO_USERNAME` and `SUDO_PASSWORD`

https://github.com/eloravpn/EloraVPNManager#requirements

**Comment by abhinaisai2002** [comment]
ok will check it

**Comment by abhinaisai2002** [comment]
can i use tanstack query for this project?

**Comment by eloravpn** [comment]
I don't know this framework, what is the benefit for us in this task or this project?
please explain a little about it :heart:

**Comment by abhinaisai2002** [comment]
This library is for react, it makes the steps of fetching data simple

**Comment by eloravpn** [comment]
Okay, i saw some example of that in official site.
use it :ok:

**Comment by eloravpn** [comment]
Hi @abhinaisai2002 
How are you doing?

**Comment by eloravpn** [comment]
Duplicated by #17
