### ISSUE TITLE
nothing will apear

### ISSUE THREAD

**Issue by mohkhz2001** [eloravpn/EloraVPNManager#31]
سلام وقت بخیر
متاسفانه هیچی نمایش داده نمیشه.
![Screenshot_20240107_185759](https://github.com/eloravpn/EloraVPNManager/assets/56700076/ddde6295-a4b6-4917-a178-03b0345d6353)
![Screenshot_20240107_185834](https://github.com/eloravpn/EloraVPNManager/assets/56700076/e3095746-13ff-4235-9a89-098bdd0666b1)

**Comment by eloravpn** [comment]
Install Web Pannel
Follow the Readme in [Elora VPN Manager Panel](https://github.com/eloravpn/EloraVPNManagerPanel)
