### ISSUE TITLE
مانیتور ترافیک و درج آن در پنل

### ISSUE THREAD

**Issue by DrWampire** [eloravpn/EloraVPNManager#44]
با سلام وقت بخیر ،

اول اینکه خیلی ممنون از اینکه زحمت کشدین همچین پنلی طراحی کردین واقعا خسته نباشید میگم

و در مورد دوم اینکه من به یک مشکلی برخوردم که واقعا فکرم نمیرسه دیگه چجوری حلش کنم من تمام کارای پنل رو به جهت استفاده و تست انجام دادم

کانکشن و سابسکریپشن همه چی داره به خوبی کار میکنه ولی فقط بخش سنجش ترافیک استفاده شده کاملا بی حرکت هستش بنده روی مقدار 1 گیگ قرار دادم و هرچقدر مصرف کردم حتی بیشتر از 1 گیگ هیچ تغییری توی مقدار پنل Elora نکرد و فقط مقدار در پنل X-UI سنایی تغییر پیدا کرده

و جدا از این مورد اشتراک ها با اینکه رو حالت ترافیکی تنظیم شده توی تمامی بخش های کانفینگی ولی چیزی در پنل X-UI سنایی هم ساخته میشه چه از تاریخ و چه از ترافیک هردو نامحدود هستن

بنده چون پنل و اسکریپت سانیی رو روی یک سرور زده بودم گفتم شاید باگ گرفته باشه از همین بابت یک سرور دیگه ساختم و پنل سنایی دیگه ای روی اون زدم و مجدد ( حتی بدون تانل ) هم تست کردم هیچ تغییری روی مقدار حجم مصرف شده زده نشد در Elora

و محدودیت زمانی رو هنوز تست نشده

ممنون میشم زحمت بکشین راهنمایی کنین ، سپاسگزارم.

**Comment by eloravpn** [comment]
درود
کلیه محدودیت زمانی و ترافیکی در پنل محاسبه می گردد.
بروزرسانی ترافیک به صورت دیفالت هر یک ساعت یکبار در پنل انجام می شود.
این مورد در فایل .env قابل تنظیم هست.
روند به این صورت هست که مصرف هر اشتراک در نود های مختلف به صورت ساعتی تجمیع می گردد و در صورت لزوم پس از اتمام زمان یا ترافیک اشتراک در تمامی نود های غیرفعال می گردد.

**Comment by DrWampire** [comment]
ممنونم از پاسخگوییتون

میشه بی زحمت بفرمایید کدوم مورد در این فایل مربوط به این موضوع هستش؟

من sudo nano /opt/elora-vpn/.env فایل رو باز میکنم و تنها چیزی که به چشم میخوره که احتمال داره برای بازه زمانی باشه

JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440

این دو مورد هستن و اینکه مقدارش به چه صورته برای وارد کردنش

من مشکلی ندارم از این جانب که بخواد منابع مصرف کنه برای برسی ترافیک ها و ساختن سریعتر کانکشن ها

درصورت امکان ممنون میشم راهنمایی بفرمایید که به چه صورت میشه حلشون کرد.

سپاسگزارم.

**Comment by eloravpn** [comment]
ریست کردن مکرر ترافیک باعث کندی در نود ها می شه.
اینجا منبع کل تنظیمات هست:
https://github.com/eloravpn/EloraVPNManager/blob/main/src/config.py

برای تنظیم این مورد بر اساس زمان دلخواه می تونید این تنظیم را در فایل .env بر اساس ثانیه تنظیم کنید:
SYNC_ACCOUNTS_TRAFFIC_INTERVAL 
پیش فرض 3600 ثانیه یا یک ساعت هست.
