### ISSUE TITLE
uuid تکراری

### ISSUE THREAD

**Issue by mohi18217** [eloravpn/EloraVPNManager#54]
سلام. در پنل وقتی میخوای به یک یوزر اکانت دیگه ای اضافه کنی همون uuid اکانت اول رو میاره و ایجاد با خطا روبرو میشه. وقتی از پنل خارج بشی و دوباره لاگین کنی مشکل حل میشه

**Comment by eloravpn** [comment]
Hi @mohi18217, could you please install the latest version and confirm if this issue has been resolved?
