### ISSUE TITLE
ارور در رمز و پسورد ادمین

### ISSUE THREAD

**Issue by erfanesmizadh** [eloravpn/EloraVPNManager#58]
![Screenshot_۲۰۲۴۱۲۱۱_۰۸۱۵۴۲_com_android_chrome_CustomTabActivity](https://github.com/user-attachments/assets/d4192a14-b2a0-4021-be2b-d7ad9bcb6389)

**Comment by erfanesmizadh** [comment]
چنین اروری بهم میده بی زحمت راهنمایی کنین

**Comment by eloravpn** [comment]
سلام
محتویات فایل .env و config.json را ارسال نمایید.
احتمالا این دو فایل بدرستی تنظیم نشده است.
ویدئو راهنمای نصب را مشاهده کردید؟

**Comment by erfanesmizadh** [comment]
پنل بالا میادش برام خیلی تمیز رمز پسورد سدو و میزنم وارد پنل میشم

**Comment by erfanesmizadh** [comment]
اصلا امکان لاگین به پنل ادمین های غیر سودو وجود داره؟!

**Comment by eloravpn** [comment]
فعلا فقط یک کاربر ادمین هست
