### ISSUE TITLE
after update to version 1.3.5 got errors

### ISSUE THREAD

**Issue by bostps** [eloravpn/EloraVPNManager#64]
after update to version 1.3.5 got errors XHR Mixed block
its look like some GET and POST request send by http and not by https 
all certificates are installed 
all worked on version 1.3.4
now even login stuck on this error

**Comment by eloravpn** [comment]
Let me check it.

**Comment by bostps** [comment]
Blocked loading mixed active content “http://pan.xxxxxxx.biz:51897/api/admin/token”
its look like error come from here Http.js

**Comment by eloravpn** [comment]
Please install version 1.3.6 and verify its functionality.

**Comment by bostps** [comment]
Now its look good
thank you
and one more problem i see 
the traffic meter no synchronized with 3x-ui panel
on elora 0.10/2 GB (5%)
on 3x-ui 534.36 MB

**Comment by bostps** [comment]
Thank you
